import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 0.95
padding =  {x=5,y=5}
dynamic_padding = true

[font]
normal = {family="FiraMono Nerd Font", style="Normal"}
size = 12

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#11111b"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen"}]

